#!/bin/bash

echo -e "\033[42;30m INFO \033[0m Starting to delete executables generated by compilation."
find $(git rev-parse --show-toplevel) -name '*.exe' -type f -print -exec rm {} \;
echo -e "\033[42;30m INFO \033[0m Successfully deleted executables generated by compilation."

